### ISSUE TITLE
[breaking change] Remove tabs from disassembly output

### ISSUE THREAD

**Issue by PrzemekWirkus** [arm-developer-tools/windowsperf-vs-extension#9]
Cloned from: https://linaro.atlassian.net/browse/WPERF-890
---
Merge request https://gitlab.com/Linaro/WindowsPerf/windowsperf/-/merge_requests/597  potentially created a breaking change. 

Please note that we’ve removed from disassembly (sampling) JSON output strings TABs (tab characters) as these are not allowed with JSON.

DOD:
- Double check that this change has no impact on current Extension.
- If there is an impact (e.g. parsing is broken for disassembly or disassembly window text alignment is off) please fix accordingly.

**Comment by Alaaeddine-chakroun** [comment]
Did not notice any changes in disassembly output. Issue can be closed.
